### ISSUE TITLE
Feature Request: Range input

### ISSUE THREAD

**Issue by StarLederer** [timo-reymann/bash-tui-toolkit#17]
### Description

First of all, this is a really nice toolkit! Thank you for developing it!

This toolkit already covers most of what I need and looks very nice, however I am missing a range input that is critical for one of the scripts i am trying to write.

The type of input I am looking for should function similar to `--scale` from Zenity but in TUI.

I am not sure if there is a standard TUI look for scale inputs but I imagine it might looks something like the following:
```bash
$ scale "Adjust the slider" -5 5 0
? Adjust the slider
-5 ❮ 0 ❯ 5
```

**Comment by timo-reymann** [comment]
Heya @StarLederer,

Firstly, thank you for using the TUI lib! :) 
Your suggestion sounds like a neat addition.

I will work on it in the following days but can't promise anything, especially since this requires testing on all supported platforms (and probably some weird combinations as well)

Cheers,
Timo

**Comment by timo-reymann** [comment]
Works like a charm with no changes on every platform 🚀 

Could reuse a lot from list and select infra, concepts. Will be included in next release.

**Comment by StarLederer** [comment]
Awesome 🎉
